### ISSUE TITLE
Per node-type permissions

### ISSUE THREAD

**Issue by hilmiller** [hpcsi/losf#40]
I think the [Permissions] section should have the ability to define permissions per node type, just like the [Services] section. I hope this doesn't seem knit-picky, I'm wrestling with the fine-grained filesystem permissions of a hadoop cluster at the moment.

**Comment by koomie** [comment]
This request is a duplicate of #66.

**Comment by koomie** [comment]
Hil,

This feature has been added to the level branch and will be available in the forthcoming 0.51.0 release.
