### ISSUE TITLE
Unexpected addpkg "already installed"

### ISSUE THREAD

**Issue by hilmiller** [hpcsi/losf#50]
For example, I just installed a package on login1 called ldapvi. Now that the package is installed on the host and I see that it works as expected, I want to add the package to the node-definition "login". However, that does not work as expected. The work-around is I have to go to login2 to add the package there, where it doesn't exist yet, to add that package to the node-type "login". This seems like an undesired work-flow or bug to me.

```
[root@login1.cluster]# losf addpkg ldapvi

** Checking on possible addition of requested distro package: ldapvi
   --> Underlying package manager = yum
   --> package ldapvi is already installed locally

[ERROR]:    --> use updatepkg to check for a newer distro version
```

**Comment by koomie** [comment]
Sorry I left this one open so long. The use case you describe is really problematic for the dependency tracking approach adopted by LosF. Although, we could alter the behavior to let it add this OS package (that was installed via standalone methods), it would open up a new can of worms and potentially get you into more trouble in the long run. Think about the case where, as part of the process to install your "sl" package, the package manager had to install 15 other dependencies. If you come in later and want to "losf addpkg sl", even if we allowed it, there is no good way to know that it also needs to track the 15 dependencies as well.
