### ISSUE TITLE
Can't use an undefined value as an ARRAY reference error

### ISSUE THREAD

**Issue by ltbranch** [hpcsi/losf#64]
Hi Karl,
Can you comment on this error and the fix? I know we've seen this in the past but don't recall how to fix it. We think it was something about reingesting the slurm history into losf? Do you know what causes this error?

[root@master.stampede]# losf hlog c557-203
Can't use an undefined value as an ARRAY reference at /admin/build/admin/losf-0.47.3/utils//LosF_history_utils.pm line 165.

**Comment by hilmiller** [comment]
Looks like our "/admin/build/admin/hpc_stack/.losf_log_data" is corrupted. This code returns nothing, which means the array at line 165 in LosF_history_utils.pm is undefined which creates the error.

```
#!/usr/bin/env perl

use Storable qw(store retrieve nstore nstore_fd lock_retrieve lock_nstore);
use Fcntl    qw(:DEFAULT :flock);
use Data::Dumper;
use File::Temp qw/tempfile/;
#use strict;
#use warnings;
#dont judge me

my $DATA_FILE="/admin/build/admin/hpc_stack/.losf_log_data";
($DATA_VERSION,%node_history) = @{retrieve ($DATA_FILE)};
print %node_history;
```

However when we use an older $DATA_FILE just as ".losf_log_data_2014-02-21" it returns a ton of logs as expected.

```
#!/usr/bin/env perl

use Storable qw(store retrieve nstore nstore_fd lock_retrieve lock_nstore);
use Fcntl    qw(:DEFAULT :flock);
use Data::Dumper;
use File::Temp qw/tempfile/;
#use strict;
#use warnings;
#dont judge me

my $DATA_FILE="/admin/build/admin/hpc_stack/.losf_log_data_2014-02-21";
($DATA_VERSION,%node_history) = @{retrieve ($DATA_FILE)};
print %node_history;
```

So maybe the question is, how do we find what mischief got into .losf_log_data ... not sure, maybe Data::Dumper module has the ability to give us more debug information about what is broken in the data's structure. Might be something to look into later if anyone has the time.

**Comment by koomie** [comment]
Hi Laura,

I believe Hil is correct here - something must have corrupted the back-end file (.losf_log_data). There is a lock which should prevent it from multi-threading usage (e.g. two admins adding logs at the same time), but if something else went south while it was updating the file (say process interrupted), that could do it.

You will probably want to re-ingest from the latest slurm logs, and there are some utils sitting around on Stampede for this. Let me see if I can find them and follow up….

-k

**Comment by ltbranch** [comment]
So I guess we need to recreate .losf_log_data? I attempted earlier removing .losf_log_data.lock but that didn't change anything. The timestamp is Mar 20. What happens if you remove .losf_log_data (move to another location)? Will losf recreate this file? Also should this file be in ~build/admin/hpc_stack? It was my understanding everything had moved to ~build/admin/losf and ~build/admin/config?

Thanks in advance!

**Comment by koomie** [comment]
That’s correct; if you delete it, it won’t recreate it and you won’t have all the slurm history. I’m working to see if I recreate it now and will follow up with the steps…..

-k

**Comment by hilmiller** [comment]
I should have said the Storable module might know what is going on, but it disappointingly has very little reporting on the data file itself. Looks like rebuild is the way to go.

**Comment by koomie** [comment]
Provided instructions for TACC to recreate hlog history from raw slum logs.
