### ISSUE TITLE
koomie_cf support for Centos/RHEL 7?

### ISSUE THREAD

**Issue by davidcarver** [hpcsi/losf#79]
koomie_cf support for Centos/RHEL 7?
It looks like getopts.pl has been dropped from CentOS 7 and perl 5.16.3

[root@master etc]# koomie_cf.pl -help
Can't locate getopts.pl in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /admin/build/admin/losf/utils/koomie_cf.pl line 29.

[root@master etc]# cat /etc/system-release
CentOS Linux release 7.1.1503 (Core) 

[root@master etc]# perl -version
This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi
(with 28 registered patches, see perl -V for more detail)

Thanks!
David

**Comment by koomie** [comment]
Hi David,

Any chance you are using an old version of losf?  That was resolved a while ago (see #60) and newer versions should work with that rhel7 version.

**Comment by davidcarver** [comment]
Yes!  There is a very good chance since copied it off Stamped/Maverick.
[root@master admin]# which koomie_cf.pl
/admin/build/admin/losf/utils/koomie_cf.pl

[root@master admin]# ls -ld /admin/build/admin/losf
lrwxrwxrwx 1 root root 11 Nov  4 12:06 /admin/build/admin/losf -> losf-0.47.3

Let me install the latest version of losf  and let you know if that resolved the issue.

Sorry and thanks,
David
